<?php

namespace Database\Seeders;

use App\Models\Auction;
use Illuminate\Database\Seeder;

class AuctionSeeder extends Seeder
{
    public function run(): void
    {
        // Truncate the table first to prevent duplicates
        Auction::truncate();

        // Create regular auctions
        Auction::factory(15)->create();

        // Create featured auctions
        Auction::factory(3)->featured()->create();

        // Create urgent auctions
        Auction::factory(2)->urgent()->create();

        // Create sold auctions
        Auction::factory(5)->sold()->create();

        // Create specific sample auctions with detailed information
        $this->createSampleAuctions();
    }

    private function createSampleAuctions(): void
    {
        // Sample 1: Rumah Mewah
        Auction::create([
            'title' => 'Rumah Mewah 2 Lantai di Pangkalpinang',
            'description' => 'Rumah mewah dengan desain modern, dilengkapi dengan taman yang asri dan kolam renang pribadi. Lokasi strategis di pusat kota Pangkalpinang.',
            'auction_number' => 'LEL/2026/0001',
            'object_number' => 'OBJ-2026-001',
            'asset_type' => 'rumah',
            'asset_category' => 'Rumah Mewah Type 120',
            'asset_description' => 'Rumah 2 lantai dengan 4 kamar tidur, 3 kamar mandi, ruang tamu, ruang keluarga, dapur, garasi 2 mobil, taman depan dan belakang, serta kolam renang.',
            'certificate_type' => 'SHM',
            'certificate_number' => '1234/2020/SHM',
            'certificate_date' => '2020-05-15',
            'certificate_issued_by' => 'BPN Kota Pangkalpinang',
            'land_area' => 300.00,
            'building_area' => 250.00,
            'building_condition' => 'Sangat Baik',
            'floors' => 2,
            'bedrooms' => 4,
            'bathrooms' => 3,
            'parking_spaces' => 2,
            'year_built' => 2018,
            'address' => 'Jl. Soekarno Hatta No. 45',
            'village' => 'Bukit Intan',
            'district' => 'Pangkalpinang Kota',
            'city' => 'Pangkalpinang',
            'province' => 'Kepulauan Bangka Belitung',
            'postal_code' => '33115',
            'latitude' => -2.1316,
            'longitude' => 106.1168,
            'debtor_name' => 'PT. Maju Bersama',
            'debtor_id_number' => '1234567890123456',
            'debtor_address' => 'Jl. Ahmad Yani No. 123, Pangkalpinang',
            'auction_type' => 'eksekusi_hak_tanggungan',
            'auction_method' => 'lelang_terbuka',
            'auction_date' => now()->addDays(30)->setTime(10, 0, 0),
            'auction_time' => '10:00:00',
            'auction_location' => 'Kantor BPRS Babel',
            'auction_address' => 'Jl. Jenderal Sudirman No. 1, Pangkalpinang',
            'registration_start' => now()->addDays(5),
            'registration_end' => now()->addDays(27),
            'registration_requirements' => "1. KTP/Identitas yang masih berlaku\n2. NPWP\n3. Surat keterangan domisili\n4. Bukti kemampuan finansial minimal Rp 300.000.000\n5. Uang jaminan Rp 150.000.000",
            'registration_procedure' => "1. Mengisi formulir pendaftaran di kantor BPRS Babel\n2. Melengkapi dokumen persyaratan\n3. Menyetor uang jaminan ke rekening yang ditentukan\n4. Mendapat kartu peserta lelang\n5. Mengikuti penjelasan lelang sehari sebelum pelaksanaan",
            'limit_price' => 1500000000.00,
            'estimated_price' => 1800000000.00,
            'deposit_amount' => 150000000.00,
            'deposit_percentage' => 10.00,
            'increment_amount' => 10000000.00,
            'bank_name' => 'Bank Mandiri',
            'bank_branch' => 'Pangkalpinang',
            'account_number' => '1234567890',
            'account_holder' => 'BPRS Babel',
            'creditor_name' => 'BPRS Babel',
            'creditor_address' => 'Jl. Jenderal Sudirman No. 1, Pangkalpinang',
            'legal_basis' => 'Undang-Undang No. 4 Tahun 1996 tentang Hak Tanggungan',
            'court_decision' => 'Putusan PN Pangkalpinang No. 123/Pdt.G/2023/PN.Pkp',
            'court_decision_date' => '2023-08-15',
            'debt_amount' => 1200000000.00,
            'encumbrance_details' => 'Hak Tanggungan Peringkat 1 atas nama BPRS Babel',
            'viewing_start' => now()->addDays(10),
            'viewing_end' => now()->addDays(29),
            'viewing_schedule' => "Senin - Jumat: 09:00 - 15:00 WIB\nSabtu: 09:00 - 12:00 WIB\nMinggu: Libur",
            'viewing_contact' => 'Budi Santoso - 0812-3456-7890',
            'viewing_notes' => 'Harap konfirmasi H-1 sebelum datang untuk viewing. Maksimal 5 orang per sesi.',
            'terms_conditions' => "1. Peserta lelang wajib memenuhi persyaratan yang ditentukan\n2. Keputusan pemenang lelang bersifat final dan tidak dapat diganggu gugat\n3. Pelunasan maksimal 30 hari setelah lelang\n4. Objek lelang dijual dalam kondisi apa adanya (as is where is)\n5. Segala biaya administrasi, pajak, dan biaya lainnya ditanggung pembeli\n6. Apabila pemenang mengundurkan diri, uang jaminan hangus",
            'special_conditions' => 'Objek lelang bebas dari sengketa dan siap untuk ditempati',
            'payment_terms' => 'Pelunasan dapat dilakukan secara tunai atau dengan fasilitas KPR bank yang bekerja sama',
            'payment_deadline_days' => 30,
            'delivery_terms' => 'Penyerahan objek dilakukan setelah pelunasan dan penyelesaian administrasi',
            'organizer_name' => 'BPRS Babel',
            'organizer_type' => 'Bank Pembiayaan Rakyat Syariah',
            'organizer_address' => 'Jl. Jenderal Sudirman No. 1, Pangkalpinang',
            'organizer_phone' => '0717-123456',
            'organizer_email' => 'info@bprsbabel.co.id',
            'organizer_website' => 'https://bprsbabel.co.id',
            'contact_person' => 'Ahmad Fauzi',
            'contact_position' => 'Manager Operasional',
            'contact_phone' => '0717-123456',
            'contact_email' => 'ahmad.fauzi@bprsbabel.co.id',
            'contact_whatsapp' => '0812-1234-5678',
            'contact_office_hours' => 'Senin - Jumat: 08:00 - 16:00 WIB, Sabtu: 08:00 - 12:00 WIB',
            'facilities' => 'Listrik PLN 2200 VA, Air PDAM, Telepon, Internet Fiber, AC di setiap ruangan, Water Heater, Kolam Renang, Taman',
            'nearby_facilities' => 'Sekolah Internasional (500m), Rumah Sakit Umum (1km), Mall Pangkalpinang (2km), Bank (300m), Masjid (200m)',
            'transportation_access' => 'Akses mudah ke jalan utama, dekat dengan terminal dan bandara. Transportasi umum tersedia.',
            'investment_potential' => 'Lokasi strategis di pusat kota dengan potensi kenaikan nilai tinggi. Cocok untuk investasi jangka panjang atau tempat tinggal mewah.',
            'market_analysis' => 'Harga properti di area ini mengalami kenaikan 8-10% per tahun. Demand tinggi untuk rumah mewah.',
            'risk_factors' => 'Risiko minimal karena lokasi strategis dan kondisi bangunan sangat baik.',
            'meta_title' => 'Lelang Rumah Mewah 2 Lantai Pangkalpinang - BPRS Babel',
            'meta_description' => 'Lelang rumah mewah 2 lantai dengan kolam renang di Pangkalpinang. Harga limit Rp 1.5 Miliar. Info lengkap di BPRS Babel.',
            'meta_keywords' => 'lelang rumah, rumah mewah pangkalpinang, properti babel, bprs babel',
            'status' => 'upcoming',
            'published_at' => now(),
            'is_featured' => true,
            'featured_until' => now()->addDays(60),
            'is_urgent' => false,
            'sort_order' => 1,
            'view_count' => 245,
            'interest_count' => 18,
            'download_count' => 32,
        ]);

        // Sample 2: Ruko Strategis
        Auction::create([
            'title' => 'Ruko 3 Lantai Strategis di Jalan Utama Sungailiat',
            'description' => 'Ruko 3 lantai dengan lokasi sangat strategis di jalan utama Sungailiat. Cocok untuk berbagai jenis usaha dengan traffic tinggi.',
            'auction_number' => 'LEL/2026/0002',
            'object_number' => 'OBJ-2026-002',
            'asset_type' => 'ruko',
            'asset_category' => 'Ruko Corner 3 Lantai',
            'asset_description' => 'Ruko corner 3 lantai dengan luas tanah 120 m² dan luas bangunan 300 m². Lantai 1 untuk usaha, lantai 2-3 untuk kantor atau gudang.',
            'certificate_type' => 'SHGB',
            'certificate_number' => '5678/2019/SHGB',
            'certificate_date' => '2019-03-20',
            'certificate_issued_by' => 'BPN Kabupaten Bangka',
            'land_area' => 120.00,
            'building_area' => 300.00,
            'building_condition' => 'Baik',
            'floors' => 3,
            'bedrooms' => null,
            'bathrooms' => 4,
            'parking_spaces' => 3,
            'year_built' => 2015,
            'address' => 'Jl. Jenderal Sudirman No. 88',
            'village' => 'Sungailiat',
            'district' => 'Sungailiat',
            'city' => 'Sungailiat',
            'province' => 'Kepulauan Bangka Belitung',
            'postal_code' => '33211',
            'latitude' => -1.8667,
            'longitude' => 106.1167,
            'debtor_name' => 'CV. Berkah Jaya',
            'debtor_id_number' => '9876543210987654',
            'debtor_address' => 'Jl. Pahlawan No. 67, Sungailiat',
            'auction_type' => 'eksekusi_fidusia',
            'auction_method' => 'lelang_terbuka',
            'auction_date' => now()->addDays(45)->setTime(14, 0, 0),
            'auction_time' => '14:00:00',
            'auction_location' => 'Kantor BPRS Babel Cabang Sungailiat',
            'auction_address' => 'Jl. Ahmad Yani No. 45, Sungailiat',
            'registration_start' => now()->addDays(7),
            'registration_end' => now()->addDays(42),
            'registration_requirements' => "1. KTP/Identitas yang masih berlaku\n2. NPWP\n3. Surat keterangan domisili\n4. Bukti kemampuan finansial minimal Rp 200.000.000\n5. Uang jaminan Rp 120.000.000",
            'registration_procedure' => "1. Mengisi formulir pendaftaran\n2. Melengkapi dokumen persyaratan\n3. Menyetor uang jaminan\n4. Mendapat kartu peserta lelang",
            'limit_price' => 800000000.00,
            'estimated_price' => 950000000.00,
            'deposit_amount' => 120000000.00,
            'deposit_percentage' => 15.00,
            'increment_amount' => 5000000.00,
            'bank_name' => 'Bank Mandiri',
            'bank_branch' => 'Sungailiat',
            'account_number' => '0987654321',
            'account_holder' => 'BPRS Babel Cabang Sungailiat',
            'creditor_name' => 'BPRS Babel',
            'creditor_address' => 'Jl. Ahmad Yani No. 45, Sungailiat',
            'legal_basis' => 'Undang-Undang No. 42 Tahun 1999 tentang Fidusia',
            'court_decision' => 'Putusan PN Sungailiat No. 456/Pdt.G/2023/PN.Slt',
            'court_decision_date' => '2023-09-20',
            'debt_amount' => 650000000.00,
            'encumbrance_details' => 'Fidusia atas nama BPRS Babel',
            'viewing_start' => now()->addDays(12),
            'viewing_end' => now()->addDays(44),
            'viewing_schedule' => "Senin - Jumat: 09:00 - 16:00 WIB\nSabtu: 09:00 - 13:00 WIB",
            'viewing_contact' => 'Siti Aminah - 0717-654321',
            'viewing_notes' => 'Konfirmasi terlebih dahulu sebelum datang viewing',
            'terms_conditions' => "1. Peserta lelang wajib memenuhi persyaratan\n2. Keputusan pemenang bersifat final\n3. Pelunasan maksimal 30 hari\n4. Objek dijual apa adanya\n5. Biaya administrasi ditanggung pembeli",
            'special_conditions' => 'Objek lelang dalam kondisi terawat dan siap pakai untuk usaha',
            'payment_terms' => 'Pelunasan tunai atau dengan fasilitas KPR',
            'payment_deadline_days' => 30,
            'delivery_terms' => 'Penyerahan setelah pelunasan dan administrasi selesai',
            'organizer_name' => 'BPRS Babel Cabang Sungailiat',
            'organizer_type' => 'Bank Pembiayaan Rakyat Syariah',
            'organizer_address' => 'Jl. Ahmad Yani No. 45, Sungailiat',
            'organizer_phone' => '0717-654321',
            'organizer_email' => 'sungailiat@bprsbabel.co.id',
            'organizer_website' => 'https://bprsbabel.co.id',
            'contact_person' => 'Siti Aminah',
            'contact_position' => 'Account Officer',
            'contact_phone' => '0717-654321',
            'contact_email' => 'siti.aminah@bprsbabel.co.id',
            'contact_whatsapp' => '0812-6543-2109',
            'contact_office_hours' => 'Senin - Jumat: 08:00 - 16:00 WIB, Sabtu: 08:00 - 13:00 WIB',
            'facilities' => 'Listrik PLN 3 Phase, Air PDAM, Telepon, Internet, AC, CCTV',
            'nearby_facilities' => 'Pasar Tradisional (100m), Bank (50m), Sekolah (300m), Puskesmas (500m)',
            'transportation_access' => 'Akses mudah ke jalan utama, dekat terminal dan pelabuhan',
            'investment_potential' => 'Lokasi sangat strategis untuk usaha retail, restoran, atau kantor. ROI tinggi dengan traffic padat.',
            'market_analysis' => 'Harga ruko di area ini stabil dengan kenaikan 5-7% per tahun',
            'risk_factors' => 'Risiko rendah karena lokasi strategis dan kondisi bangunan baik',
            'meta_title' => 'Lelang Ruko 3 Lantai Strategis Sungailiat - BPRS Babel',
            'meta_description' => 'Lelang ruko 3 lantai di lokasi strategis Sungailiat. Harga limit Rp 800 Juta. Cocok untuk usaha dengan traffic tinggi.',
            'meta_keywords' => 'lelang ruko, ruko sungailiat, properti komersial, bprs babel',
            'status' => 'upcoming',
            'published_at' => now()->subDays(5),
            'is_featured' => false,
            'is_urgent' => false,
            'sort_order' => 2,
            'view_count' => 156,
            'interest_count' => 12,
            'download_count' => 8,
        ]);

        // Sample 3: Tanah Komersial
        Auction::create([
            'title' => 'Tanah Komersial 1000 m² di Toboali',
            'description' => 'Tanah komersial dengan lokasi strategis di pusat kota Toboali. Cocok untuk pembangunan mall, hotel, atau perkantoran.',
            'auction_number' => 'LEL/2026/0003',
            'object_number' => 'OBJ-2026-003',
            'asset_type' => 'tanah',
            'asset_category' => 'Tanah Komersial',
            'asset_description' => 'Tanah kosong seluas 1000 m² dengan topografi datar, cocok untuk pembangunan gedung bertingkat. Akses jalan lebar 12 meter.',
            'certificate_type' => 'SHM',
            'certificate_number' => '9999/2021/SHM',
            'certificate_date' => '2021-06-10',
            'certificate_issued_by' => 'BPN Kabupaten Bangka Selatan',
            'land_area' => 1000.00,
            'building_area' => null,
            'building_condition' => null,
            'floors' => null,
            'bedrooms' => null,
            'bathrooms' => null,
            'parking_spaces' => null,
            'year_built' => null,
            'address' => 'Jl. Raya Toboali KM 5',
            'village' => 'Toboali',
            'district' => 'Toboali',
            'city' => 'Toboali',
            'province' => 'Kepulauan Bangka Belitung',
            'postal_code' => '33613',
            'latitude' => -2.8667,
            'longitude' => 106.6167,
            'debtor_name' => 'PT. Investasi Properti Nusantara',
            'debtor_id_number' => '1122334455667788',
            'debtor_address' => 'Jl. Merdeka No. 234, Toboali',
            'auction_type' => 'eksekusi_hak_tanggungan',
            'auction_method' => 'lelang_terbuka',
            'auction_date' => now()->addDays(60)->setTime(10, 0, 0),
            'auction_time' => '10:00:00',
            'auction_location' => 'Kantor BPRS Babel Cabang Toboali',
            'auction_address' => 'Jl. Diponegoro No. 12, Toboali',
            'registration_start' => now()->addDays(15),
            'registration_end' => now()->addDays(57),
            'registration_requirements' => "1. KTP/Identitas yang masih berlaku\n2. NPWP\n3. Surat keterangan domisili\n4. Bukti kemampuan finansial minimal Rp 500.000.000\n5. Uang jaminan Rp 400.000.000",
            'registration_procedure' => "1. Mengisi formulir pendaftaran\n2. Melengkapi dokumen persyaratan\n3. Menyetor uang jaminan\n4. Mendapat kartu peserta lelang\n5. Mengikuti penjelasan lelang",
            'limit_price' => 2000000000.00,
            'estimated_price' => 2500000000.00,
            'deposit_amount' => 400000000.00,
            'deposit_percentage' => 20.00,
            'increment_amount' => 25000000.00,
            'bank_name' => 'Bank Mandiri',
            'bank_branch' => 'Toboali',
            'account_number' => '5555666677',
            'account_holder' => 'BPRS Babel Cabang Toboali',
            'creditor_name' => 'BPRS Babel',
            'creditor_address' => 'Jl. Diponegoro No. 12, Toboali',
            'legal_basis' => 'Undang-Undang No. 4 Tahun 1996 tentang Hak Tanggungan',
            'court_decision' => 'Putusan PN Toboali No. 789/Pdt.G/2023/PN.Tbl',
            'court_decision_date' => '2023-10-05',
            'debt_amount' => 1600000000.00,
            'encumbrance_details' => 'Hak Tanggungan Peringkat 1 atas nama BPRS Babel',
            'viewing_start' => now()->addDays(20),
            'viewing_end' => now()->addDays(59),
            'viewing_schedule' => "Senin - Sabtu: 08:00 - 17:00 WIB\nMinggu: Libur",
            'viewing_contact' => 'Bambang Wijaya - 0717-789012',
            'viewing_notes' => 'Lokasi mudah diakses, harap koordinasi untuk viewing bersama',
            'terms_conditions' => "1. Peserta lelang wajib memenuhi persyaratan\n2. Keputusan pemenang bersifat final\n3. Pelunasan maksimal 30 hari\n4. Objek dijual apa adanya\n5. Biaya administrasi, pajak, dan notaris ditanggung pembeli\n6. Pembeli bertanggung jawab atas IMB dan perizinan",
            'special_conditions' => 'Tanah bebas sengketa, siap untuk pembangunan komersial',
            'payment_terms' => 'Pelunasan tunai atau dengan fasilitas kredit konstruksi',
            'payment_deadline_days' => 30,
            'delivery_terms' => 'Penyerahan tanah setelah pelunasan dan balik nama sertifikat',
            'organizer_name' => 'BPRS Babel Cabang Toboali',
            'organizer_type' => 'Bank Pembiayaan Rakyat Syariah',
            'organizer_address' => 'Jl. Diponegoro No. 12, Toboali',
            'organizer_phone' => '0717-789012',
            'organizer_email' => 'toboali@bprsbabel.co.id',
            'organizer_website' => 'https://bprsbabel.co.id',
            'contact_person' => 'Bambang Wijaya',
            'contact_position' => 'Branch Manager',
            'contact_phone' => '0717-789012',
            'contact_email' => 'bambang.wijaya@bprsbabel.co.id',
            'contact_whatsapp' => '0812-7890-1234',
            'contact_office_hours' => 'Senin - Jumat: 08:00 - 16:00 WIB, Sabtu: 08:00 - 14:00 WIB',
            'facilities' => 'Akses jalan aspal lebar 12m, listrik PLN tersedia, air PDAM tersedia',
            'nearby_facilities' => 'Pusat Perbelanjaan (200m), Rumah Sakit (500m), Sekolah (300m), Bank (100m), Kantor Pemerintahan (1km)',
            'transportation_access' => 'Akses mudah dari jalan utama, dekat dengan pelabuhan dan bandara',
            'investment_potential' => 'Lokasi strategis untuk pembangunan komersial. Potensi ROI tinggi dengan pertumbuhan ekonomi Toboali yang pesat.',
            'market_analysis' => 'Harga tanah komersial di Toboali mengalami kenaikan 12-15% per tahun. Demand tinggi untuk lahan komersial.',
            'risk_factors' => 'Risiko minimal, lokasi strategis dengan infrastruktur lengkap',
            'meta_title' => 'Lelang Tanah Komersial 1000m² Toboali - BPRS Babel',
            'meta_description' => 'Lelang tanah komersial strategis 1000m² di Toboali. Harga limit Rp 2 Miliar. Cocok untuk mall, hotel, perkantoran.',
            'meta_keywords' => 'lelang tanah, tanah komersial toboali, investasi properti, bprs babel',
            'status' => 'upcoming',
            'published_at' => now()->subDays(2),
            'is_featured' => false,
            'is_urgent' => true,
            'sort_order' => 3,
            'view_count' => 89,
            'interest_count' => 8,
            'download_count' => 5,
        ]);
    }
}
