<?php

return [
    'sql_injection' => [
        '/\bunion\s+(all\s+)?select\b/i',
        '/\bselect\b.+\bfrom\b.+\bwhere\b/i',
        '/\binsert\s+into\b/i',
        '/\bdelete\s+from\b/i',
        '/\bdrop\s+(table|database|index)\b/i',
        '/\btruncate\s+table\b/i',
        '/\balter\s+table\b/i',
        '/\bexec(\s+|\()xp_/i',
        '/\bexecute\s+immediate\b/i',
        '/\'\s*(or|and)\s+[\'"]?\d+[\'"]?\s*=\s*[\'"]?\d+/i',
        '/\'\s*(or|and)\s+[\'"]?[a-z]+[\'"]?\s*=\s*[\'"]?[a-z]+/i',
        '/\bor\b\s+1\s*=\s*1/i',
        '/\band\b\s+1\s*=\s*1/i',
        '/\bwaitfor\s+delay\b/i',
        '/\bbenchmark\s*\(/i',
        '/\bsleep\s*\(\s*\d+\s*\)/i',
        '/;\s*(select|insert|update|delete|drop|create|alter|exec)/i',
        '/\/\*[\s\S]*?\*\//i',
        '/--\s*$/m',
        '/\b(char|nchar|varchar|nvarchar)\s*\(/i',
        '/\bconvert\s*\(/i',
        '/\bcast\s*\(/i',
        '/0x[0-9a-f]{2,}/i',
    ],

    'xss' => [
        '/<script[^>]*>.*?<\/script>/is',
        '/<script[^>]*>/i',
        '/\bon\w+\s*=\s*["\']?[^"\']+["\']?/i',
        '/javascript\s*:/i',
        '/vbscript\s*:/i',
        '/data\s*:[^,]*;base64/i',
        '/<svg[^>]*onload/i',
        '/<object[^>]*data\s*=/i',
        '/<embed[^>]*src\s*=/i',
        '/<iframe[^>]*src\s*=/i',
        '/expression\s*\(/i',
        '/eval\s*\(/i',
        '/document\s*\.\s*(cookie|write|location)/i',
        '/window\s*\.\s*(location|open)/i',
        '/innerHTML\s*=/i',
        '/&#x?[0-9a-f]+;/i',
        '/%3[cC]script/i',
    ],

    'path_traversal' => [
        '/\.\.[\/\\\\]/i',
        '/\.\.%2[fF]/i',
        '/\.\.%5[cC]/i',
        '/%2e%2e[\/\\\\%]/i',
        '/\.\.\//i',
        '/\.\.\\\/i',
        '/\/etc\/passwd/i',
        '/\/etc\/shadow/i',
        '/\/proc\/self/i',
        '/\/var\/log/i',
        '/c:\\\\windows/i',
        '/c:\\\\boot\.ini/i',
    ],

    'command_injection' => [
        '/\$\(/i',
        '/`[^`]+`/',
        '/\|\s*\w+/',
        '/;\s*\w+/',
        '/\bwget\s+/i',
        '/\bcurl\s+/i',
        '/\bnc\s+-/i',
        '/\bnetcat\b/i',
        '/\bbash\s+-/i',
        '/\bsh\s+-c/i',
        '/\bperl\s+-e/i',
        '/\bpython\s+-c/i',
        '/\bphp\s+-r/i',
        '/\bruby\s+-e/i',
    ],

    'file_inclusion' => [
        '/\binclude\s*\(/i',
        '/\brequire\s*\(/i',
        '/\binclude_once\s*\(/i',
        '/\brequire_once\s*\(/i',
        '/\bfile_get_contents\s*\(/i',
        '/\bfopen\s*\(/i',
        '/\breadfile\s*\(/i',
        '/php:\/\/filter/i',
        '/php:\/\/input/i',
        '/expect:\/\//i',
        '/data:\/\//i',
    ],

    'scanner_agents' => [
        'sqlmap', 'nikto', 'nmap', 'masscan', 'zgrab', 'havij',
        'acunetix', 'nessus', 'openvas', 'burpsuite', 'w3af', 'wpscan',
        'dirbuster', 'gobuster', 'ffuf', 'nuclei', 'httpx', 'subfinder',
        'amass', 'whatweb', 'fierce',
    ],

    'url_attack_patterns' => [
        '/union\s+all\s+select/i',
        '/union\s+select/i',
        '/select\s+.*\s+from\s+.*\s+where\s+.*=/i',
        '/insert\s+into\s+\w+\s*\(/i',
        '/drop\s+table\s+/i',
        '/delete\s+from\s+\w+\s+where/i',
        '/update\s+\w+\s+set\s+\w+\s*=/i',
        '/exec\s*\(\s*xp_/i',
        '/;\s*drop\s/i',
        '/;\s*delete\s/i',
        '/\'\s*or\s+\'1\'\s*=\s*\'1/i',
        '/\'\s*or\s+1\s*=\s*1/i',
        '/<script[^>]*>.*<\/script>/is',
        '/javascript\s*:\s*[a-z]/i',
        '/wp-admin/i',
        '/wp-login\.php/i',
        '/xmlrpc\.php/i',
        '/phpmyadmin/i',
        '/\.env$/i',
        '/\.git\//i',
        '/\.htaccess/i',
        '/etc\/passwd/i',
        '/proc\/self/i',
    ],
];